# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('content', models.CharField(max_length=2000, verbose_name='內文')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='發佈時間')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
